---

- name: "install common packages"
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - zsh
    - vim
- name: "add the developers group"
  group:
    name: "developers"
    state: present
