---

- name: "set up the nodejs key"
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: "set up the nodejs repository"
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_14.x focal main"
    state: present

- name: "install nodejs setup"
  apt:
    name: nodejs
    state: latest
