---

- include_tasks: "debian.yml"
  when: "ansible_os_family == 'Debian'"
- include_tasks: "redhat.yml"
  when: "ansible_os_family == 'RedHat'"

- name: "add the developers group"
  group:
    name: "developers"
    state: present
