---

- name: "install nginx"
  apt:
    name: nginx
    state: latest

- name: "start nginx"
  service:
    name: nginx
    state: started

- name: "add the project folder"
  copy:
    src: "./{{ site_folder }}"
    dest: "/var/www"

- name: "add the nginx configuration"
  template:
    src: "./nginx.conf.j2"
    dest: "/etc/nginx/sites-available/{{ site_folder }}"

- name: "deactivate the default nginx site"
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: "activate the new configuration"
  file:
    src: "/etc/nginx/sites-available/{{ site_folder }}"
    dest: "/etc/nginx/sites-enabled/{{ site_folder }}"
    state: link

- name: "restart nginx"
  service:
    name: nginx
    state: restarted
