---

- hosts: devmachines
  become: yes
  vars:
    required_packages: 
      - git
      - vim
      - zsh
      - nodejs
  tasks:
    - name: "install base packages"
      apt:
        name: "{{ required_packages }}"
        state: present
#      with_items: "{{ required_packages }}"

#    - name: "install git"
#      apt:
#        name: git
#        state: present
#    - name: "install vim"
#      apt:
#        name: vim
#        state: present
#    - name: "install zsh"
#      apt:
#        name: zsh
#        state: present
#    - name: "install nodejs"
#      apt:
#        name: nodejs
#        state: present
